name: mybuddys
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  flutter_login: ^5.0.0
  http: ^1.2.1
  equatable: ^2.0.5
  provider: ^6.1.2
  go_router: ^13.2.4
  flutter_snake_navigationbar: ^0.6.1
  flutter_floating_bottom_bar: ^1.2.0
  animated_icon: ^0.0.9
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  salomon_bottom_bar: ^3.3.2
  persistent_bottom_nav_bar: ^5.0.2
  flutter_chat_ui: ^1.6.12
  async: ^2.11.0
  dio: ^5.4.3+1
  intl: ^0.18.1
  wolt_modal_sheet: ^0.5.0
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  custom_refresh_indicator: ^3.1.0
  geolocator: ^11.0.0
  riverpod_test: ^0.1.4
  nylo_framework: ^5.25.2
  nylo_support: ^5.64.0
  google_fonts: ^6.2.1
  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0
  url_launcher: ^6.2.6
  sliver_app_bar_builder: ^1.1.0
  babstrap_settings_screen: ^0.1.6
  icons_plus: ^5.0.0
  modal_bottom_sheet: ^3.0.0
  get_cli: ^1.8.1
  get: 4.6.6
  flutter:
    sdk: flutter
  auth_provider:
    path: auth_provider
  flutter_dotenv: ^5.1.0
  lo_form: ^0.5.0
  reactive_forms: ^16.1.1
  appwrite: ^12.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: public/assets/app_icon/icon.png
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  assets:
    - public/assets/fonts/
    - public/assets/images/
    - public/assets/app_icon/
    - lang/
    - .env
  uses-material-design: true
